all:book01 book02 book03 book04

book01:book01.cpp
	g++ -g -o book01 book01.cpp

book02:book02.cpp
	g++ -g -o book02 book02.cpp

book03:book03.cpp
	g++ -g -o book03 book03.cpp

book04:book04.cpp
	g++ -g -o book04 book04.cpp

