all:book01 book02 book03 book04 book05 book06 book07 book08 \
		tcpselect tcpclient tcppoll

PUBINCL = -I/project/public
PUBCPP = /project/public/_public.cpp

book01:book01.cpp
	g++ -g -o book01 book01.cpp

book02:book02.cpp
	g++ -g -o book02 book02.cpp

book03:book03.cpp
	g++ -g -o book03 book03.cpp

book04:book04.cpp
	g++ -g -o book04 book04.cpp

book05:book05.cpp
	g++ -g -o book05 book05.cpp

book06:book06.cpp
	g++ -g -o book06 book06.cpp

book07:book07.cpp
	g++ -g -o book07 book07.cpp -lpthread 

book08:book08.cpp
	g++ -g -o book08 book08.cpp

tcpselect:tcpselect.cpp
	g++ -g -o tcpselect tcpselect.cpp

tcpclient:tcpclient.cpp
	g++ -g -o tcpclient tcpclient.cpp

tcppoll:tcppoll.cpp
	g++ -g -o tcppoll tcppoll.cpp
